AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MyFunction
      Handler: exercise3.handler
      Runtime: nodejs18.x
      CodeUri: ./src
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          COMMON_VAR: 'This is a common variable'

  CommonLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: CommonLayer
      ContentUri: ./layer
      CompatibleRuntimes:
        - nodejs18.x
      Description: 'Common layer for shared code'
      RetentionPolicy: Retain
